# ruff.toml

# topo (quando arquivo é ruff.toml, sem [tool.ruff])
line-length = 120
target-version = "py311"

[lint]
# E,F: pycodestyle/pyflakes | I: isort (organiza imports)
select = ["E", "F", "I"]
ignore = []

# Ignorar nos testes:
# - F401 (imports não usados, ex.: pytest)
# - E501 (linhas longas em strings/asserts)
per-file-ignores = { "tests/**" = ["F401", "E501"] }

[lint.isort]
# trata "app" como first-party ao organizar imports
known-first-party = ["app"]
